version: '3'

services:
    # app:
    #     container_name: app
    #     image: node:17
    #     tty: true
    #     restart: always
    #     ports:
    #         - 3000:3000
    #     volumes:
    #         - ./:/app
    #     working_dir: /app
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: okarin
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017
        volumes:
            - ./mongo:/data/db
            - ./mongo:/data/configdb
